#!/usr/bin/env bash
# =============================================================================
#  make-test-pkgbuild.sh - derive a throwaway recipe that packages a BRANCH.
#
#  WHY THIS EXISTS
#    The real PKGBUILD points at a published release tarball and pins its
#    sha256. That is correct for the AUR and useless for testing a fix before
#    the release exists: building it would exercise the packaging while
#    installing the OLD code, which is the opposite of what a test is for.
#
#  WHY NOT A SECOND PKGBUILD COMMITTED NEXT TO THE FIRST
#    It would be a copy, and a copy goes stale the first time the real recipe
#    changes - silently, because nothing compares them. This derives the test
#    recipe from the real one on every run, so it cannot drift.
#
#  WHY THE RESULT MUST NEVER BE PUBLISHED
#    A branch tarball is regenerated by GitHub whenever the branch moves, so
#    its checksum is not stable and this recipe uses SKIP. On the AUR the
#    pinned sha256 of a release tarball is the only integrity anchor a user
#    has before compiling: a recipe with SKIP hands that up. The file is
#    written under build/, which is not tracked, to keep the two apart.
#
#  USAGE (on the Arch machine, not as root)
#    bash packaging/linux/arch/make-test-pkgbuild.sh [branch]
#    cd packaging/linux/arch/build
#    extra-x86_64-build          # clean chroot: proves depends=() is complete
#    namcap PKGBUILD *.pkg.tar.zst
#    sudo pacman -U spendifai-*.pkg.tar.zst
#
#  Then launch from the applications menu, NOT from a terminal: the failure
#  path being tested is the one where nobody is watching a console.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_PKGBUILD="${SCRIPT_DIR}/PKGBUILD"
OUT_DIR="${SCRIPT_DIR}/build"

[ -r "$SRC_PKGBUILD" ] || { echo "No PKGBUILD next to this script: $SRC_PKGBUILD" >&2; exit 1; }

BRANCH="${1:-$(git -C "$SCRIPT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || true)}"
if [ -z "$BRANCH" ] || [ "$BRANCH" = "HEAD" ]; then
  echo "Cannot tell which branch to package. Pass it: $0 <branch>" >&2
  exit 1
fi

# GitHub names the directory inside a branch archive after the repository and
# the branch, with every slash turned into a dash: fix/installer-reliability
# becomes spendif-ai-fix-installer-reliability. package() cd's into it, so the
# name has to be rewritten along with the source.
SRC_DIR_NAME="spendif-ai-${BRANCH//\//-}"

mkdir -p "$OUT_DIR"
cp -f "${SCRIPT_DIR}/spendifai.install" "$OUT_DIR/"

awk -v branch="$BRANCH" -v srcdir="$SRC_DIR_NAME" '
  /^source=\(/ {
    print "# TEST BUILD - branch tarball, not a release. Never publish this file."
    print "source=(\"${pkgname}-${pkgver}.tar.gz::${url}/archive/refs/heads/" branch ".tar.gz\")"
    next
  }
  /^sha256sums=\(/ {
    print "# SKIP because a branch tarball is regenerated whenever the branch moves."
    print "sha256sums=(\x27SKIP\x27)"
    next
  }
  /cd "\$\{srcdir\}\/spendif-ai-\$\{pkgver\}"/ {
    print "  cd \"${srcdir}/" srcdir "\""
    next
  }
  { print }
' "$SRC_PKGBUILD" > "${OUT_DIR}/PKGBUILD"

# A derived recipe that still points at the release would build the wrong code
# and look like it worked, so verify the rewrite actually happened.
for needle in "archive/refs/heads/${BRANCH}.tar.gz" "'SKIP'" "${SRC_DIR_NAME}"; do
  grep -qF "$needle" "${OUT_DIR}/PKGBUILD" || {
    echo "Rewrite failed: '${needle}' is not in the generated PKGBUILD." >&2
    echo "The real PKGBUILD has probably changed shape; fix this script." >&2
    exit 1
  }
done

PKGVER="$(awk -F= '/^pkgver=/ { print $2; exit }' "${OUT_DIR}/PKGBUILD")"

cat <<EOF

Test recipe written to ${OUT_DIR}/PKGBUILD
  branch:            ${BRANCH}
  source directory:  ${SRC_DIR_NAME}
  checksum:          SKIP (test only)

WARNING: the package will call itself ${PKGVER} while containing the code of
branch ${BRANCH}. That is fine for a test and wrong for anything else, so
remove it when you are done:  pacman -Rns spendifai

Next:
  cd ${OUT_DIR}
  extra-x86_64-build
  namcap PKGBUILD *.pkg.tar.zst
EOF
