#!/usr/bin/env python3
"""Render the landing-page FAQ from faq.json into every index.*.html.

Writes three generated blocks per page, each delimited by markers so the
script is idempotent and the hand-written parts of the page are never
touched:

  CSS        inside <style>, before </style>
  section    a <details> accordion, inserted before the STACK section
  JSON-LD    a schema.org FAQPage, before </head>

The visible text and the JSON-LD come from the same source, which is what
Google asks for: the markup has to mirror what the reader sees.

Usage:  python3 scripts/gen_faq.py [--check]
        --check exits 1 if any page is out of date.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "faq.json"
BASE = "https://spendif.ai/"

CSS_OPEN, CSS_CLOSE = "/* FAQ (generated by scripts/gen_faq.py) */", "/* /FAQ */"
SEC_OPEN, SEC_CLOSE = "<!-- FAQ (generated by scripts/gen_faq.py) -->", "<!-- /FAQ -->"
LD_OPEN, LD_CLOSE = "<!-- FAQ JSON-LD (generated by scripts/gen_faq.py) -->", "<!-- /FAQ JSON-LD -->"

STACK_ANCHOR = '<!-- ── STACK'

CSS = """    .faq-list { display: flex; flex-direction: column; gap: .75rem; }
    .faq-item { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); }
    .faq-item summary { cursor: pointer; padding: 1.1rem 1.4rem; font-weight: 600; font-size: .95rem;
      list-style: none; display: flex; justify-content: space-between; align-items: center; gap: 1rem; }
    .faq-item summary::-webkit-details-marker { display: none; }
    .faq-item summary::after { content: "+"; color: var(--blue); font-size: 1.3rem; line-height: 1; flex-shrink: 0; }
    .faq-item[open] summary::after { content: "\\2212"; }
    .faq-item p { color: var(--muted); font-size: .9rem; line-height: 1.65; padding: 0 1.4rem 1.25rem; margin: 0; }"""


def page_for(lang: str) -> Path:
    return ROOT / ("index.html" if lang == "it" else f"index.{lang}.html")


def url_for(lang: str) -> str:
    return BASE if lang == "it" else f"{BASE}index.{lang}.html"


def esc(text: str) -> str:
    return html.escape(text, quote=False)


def build_section(data: dict) -> str:
    rows = []
    for n, item in enumerate(data["items"]):
        opened = " open" if n == 0 else ""
        rows.append(f'      <details class="faq-item"{opened}>')
        rows.append(f'        <summary>{esc(item["q"])}</summary>')
        rows.append(f'        <p>{esc(item["a"])}</p>')
        rows.append("      </details>")
    return "\n".join([
        SEC_OPEN,
        '<section id="faq">',
        '  <div class="container">',
        f'    <div class="section-label">{esc(data["label"])}</div>',
        f'    <h2>{esc(data["heading"])}</h2>',
        f'    <p class="section-sub">{esc(data["sub"])}</p>',
        "",
        '    <div class="faq-list fade-in">',
        *rows,
        "    </div>",
        "  </div>",
        "</section>",
        "",
        '<hr class="divider">',
        SEC_CLOSE,
        "",
        "",
    ])


def build_jsonld(lang: str, data: dict) -> str:
    doc = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "inLanguage": lang,
        "url": url_for(lang),
        "mainEntity": [
            {
                "@type": "Question",
                "name": item["q"],
                "acceptedAnswer": {"@type": "Answer", "text": item["a"]},
            }
            for item in data["items"]
        ],
    }
    body = json.dumps(doc, indent=4, ensure_ascii=False).replace("</", "<\\/")
    body = "\n".join("  " + line for line in body.split("\n"))
    return "\n".join([
        f"  {LD_OPEN}",
        '  <script type="application/ld+json">',
        body,
        "  </script>",
        f"  {LD_CLOSE}",
        "",
    ])


def splice(text: str, opener: str, closer: str, block: str, anchor: str) -> str:
    """Replace an existing generated block, or insert one before `anchor`."""
    # the leading whitespace is part of the match: without it the block would
    # gain one extra indent per run and never settle
    pattern = re.compile(r"[ \t]*" + re.escape(opener) + r".*?" + re.escape(closer) + r"\n*", re.S)
    if pattern.search(text):
        return pattern.sub(block, text, count=1)
    if anchor not in text:
        raise SystemExit(f"anchor not found: {anchor!r}")
    return text.replace(anchor, block + anchor, 1)


def render(lang: str, data: dict) -> str:
    text = page_for(lang).read_text(encoding="utf-8")
    text = splice(text, CSS_OPEN, CSS_CLOSE,
                  f"    {CSS_OPEN}\n{CSS}\n    {CSS_CLOSE}\n", "  </style>")
    text = splice(text, SEC_OPEN, SEC_CLOSE, build_section(data), STACK_ANCHOR)
    text = splice(text, LD_OPEN, LD_CLOSE, build_jsonld(lang, data), "</head>")
    return text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if a page is out of date")
    args = ap.parse_args()

    languages = json.loads(SOURCE.read_text(encoding="utf-8"))["languages"]
    stale = []
    for lang, data in languages.items():
        path = page_for(lang)
        rendered = render(lang, data)
        if args.check:
            if rendered != path.read_text(encoding="utf-8"):
                stale.append(path.name)
            continue
        path.write_text(rendered, encoding="utf-8")
        print(f"{lang}  {path.name:18s} {len(data['items'])} questions")

    if args.check:
        if stale:
            print("out of date: " + ", ".join(stale) + " -- re-run scripts/gen_faq.py")
            return 1
        print(f"all {len(languages)} pages up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
