#!/usr/bin/env bash
# =============================================================================
# packaging/homebrew/update-tap.sh — publish the Homebrew cask for a release
# =============================================================================
#
# Renders packaging/homebrew/spendifai.rb with the version and the DMG checksum
# of a published GitHub Release, then commits it to the tap repository as
# Casks/spendifai.rb. Creates the tap repository on first run.
#
# After this runs, on any Mac:
#   brew tap spendifai/spendifai
#   brew trust --cask spendifai/spendifai/spendifai      # once per machine (Homebrew 6+)
#   brew install --cask --no-quarantine spendifai      # first install
#   brew update && brew upgrade --cask spendifai       # every later release
#
# USAGE
#   bash packaging/homebrew/update-tap.sh [--version X.Y.Z] [--tap-repo owner/repo]
#                                         [--dry-run]
#
#   --version    Release to publish. Defaults to the VERSION file.
#   --tap-repo   Tap repository. Defaults to spendifai/homebrew-spendifai.
#   --dry-run    Print what would happen; touch nothing remote.
#
# PREREQUISITES
#   gh (authenticated), git
#   The release vX.Y.Z must exist and carry the DMG asset. A draft release works
#   for rendering, but `brew install` cannot reach a draft — publish it first.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TEMPLATE="${SCRIPT_DIR}/spendifai.rb"

TAP_REPO="spendifai/homebrew-spendifai"
SOURCE_REPO="spendifai/spendif-ai"
VERSION=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)  VERSION="${2:?--version needs a value}"; shift ;;
    --tap-repo) TAP_REPO="${2:?--tap-repo needs a value}"; shift ;;
    --dry-run)  DRY_RUN=true ;;
    -h|--help)  sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
  shift
done

info() { echo "▶  $*"; }
ok()   { echo "✅ $*"; }
err()  { echo "❌ $*" >&2; exit 1; }
run()  { if $DRY_RUN; then echo "[DRY-RUN] $*"; else "$@"; fi; }

command -v gh  >/dev/null || err "gh is required"
command -v git >/dev/null || err "git is required"
gh auth status >/dev/null 2>&1 || err "gh is not authenticated (run: gh auth login)"
[[ -f "${TEMPLATE}" ]] || err "cask template not found at ${TEMPLATE}"

# ── Step 1 — resolve the version ────────────────────────────────────────────
if [[ -z "${VERSION}" ]]; then
  [[ -f "${REPO_ROOT}/VERSION" ]] || err "no --version given and no VERSION file"
  VERSION="$(tr -d '[:space:]' < "${REPO_ROOT}/VERSION")"
fi
TAG="v${VERSION}"
DMG="SpendifAi-${VERSION}.dmg"
info "Release: ${TAG}  ·  asset: ${DMG}"

# gh's built-in --jq keeps this script free of a jq dependency.
IS_DRAFT="$(gh release view "${TAG}" --repo "${SOURCE_REPO}" --json isDraft --jq '.isDraft' 2>/dev/null)" \
  || err "release ${TAG} not found in ${SOURCE_REPO}"

if [[ "${IS_DRAFT}" == "true" ]]; then
  echo "⚠️  ${TAG} is still a DRAFT. The cask will be written, but"
  echo "    'brew install' cannot download from a draft release."
  echo "    Publish it with: gh release edit ${TAG} --draft=false"
fi

gh release view "${TAG}" --repo "${SOURCE_REPO}" --json assets --jq '.assets[].name' \
  | grep -qx "${DMG}" || err "release ${TAG} has no asset named ${DMG}"

# ── Step 2 — checksum of the DMG ────────────────────────────────────────────
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

SHA256=""
if gh release download "${TAG}" --repo "${SOURCE_REPO}" \
     --pattern 'SHA256SUMS.txt' --dir "${WORK}" 2>/dev/null; then
  # Entries are written by `sha256sum` from the artifact download dirs, so the
  # second field looks like ./macos-dmg/SpendifAi-X.Y.Z.dmg — match on basename.
  SHA256="$(awk -v dmg="${DMG}" '{ n = $2; sub(/^\*/, "", n); sub(/.*\//, "", n); if (n == dmg) print $1 }' \
    "${WORK}/SHA256SUMS.txt" | head -1)"
fi

if [[ -z "${SHA256}" ]]; then
  info "SHA256SUMS.txt unusable — downloading ${DMG} to hash it locally (~120 MB)"
  gh release download "${TAG}" --repo "${SOURCE_REPO}" --pattern "${DMG}" --dir "${WORK}"
  SHA256="$(shasum -a 256 "${WORK}/${DMG}" | awk '{print $1}')"
fi

[[ "${SHA256}" =~ ^[a-f0-9]{64}$ ]] || err "could not determine a valid sha256 (got: '${SHA256}')"
ok "sha256 ${SHA256}"

# ── Step 3 — render the cask ────────────────────────────────────────────────
RENDERED="${WORK}/spendifai.rb"
{
  echo "# Generated by packaging/homebrew/update-tap.sh in ${SOURCE_REPO}."
  echo "# Do not edit here — edit packaging/homebrew/spendifai.rb there and re-run it."
  echo
  sed -e "s|^  version \".*\"|  version \"${VERSION}\"|" \
      -e "s|^  sha256 \".*\"|  sha256 \"${SHA256}\"|" "${TEMPLATE}"
} > "${RENDERED}"

grep -q "PLACEHOLDER" "${RENDERED}" && err "template still contains a PLACEHOLDER after rendering"
if command -v ruby >/dev/null; then
  ruby -c "${RENDERED}" >/dev/null || err "rendered cask is not valid Ruby"
fi

# ── Step 4 — make sure the tap repository exists ────────────────────────────
if gh repo view "${TAP_REPO}" >/dev/null 2>&1; then
  info "Tap repository ${TAP_REPO} already exists"
else
  info "Creating public tap repository ${TAP_REPO}"
  run gh repo create "${TAP_REPO}" --public \
    --description "Homebrew tap for Spendif.ai — brew install --cask spendifai"
fi

# ── Step 5 — commit the cask into the tap ───────────────────────────────────
if $DRY_RUN; then
  echo "[DRY-RUN] Would commit Casks/spendifai.rb (${VERSION}) to ${TAP_REPO}"
  echo "--- rendered cask ---"
  sed -n '1,12p' "${RENDERED}"
  exit 0
fi

CLONE="${WORK}/tap"
gh repo clone "${TAP_REPO}" "${CLONE}" -- --quiet 2>/dev/null || git clone --quiet \
  "https://github.com/${TAP_REPO}.git" "${CLONE}"

mkdir -p "${CLONE}/Casks"
cp "${RENDERED}" "${CLONE}/Casks/spendifai.rb"

cat > "${CLONE}/README.md" <<EOF
# Homebrew tap — Spendif.ai

Personal finance manager with local AI categorisation.
Source code: https://github.com/${SOURCE_REPO}

## Install

\`\`\`bash
brew tap ${TAP_REPO%%/*}/${TAP_REPO##*-}
brew trust --cask ${TAP_REPO%%/*}/${TAP_REPO##*-}/spendifai
brew install --cask --no-quarantine spendifai
\`\`\`

Homebrew 6 refuses to load casks from third-party taps until you trust them,
hence the \`brew trust\` line. \`--no-quarantine\` is required while the DMG
ships unsigned.

## Update

\`\`\`bash
brew update
brew upgrade --cask spendifai
\`\`\`

## Uninstall

\`\`\`bash
brew uninstall --cask spendifai        # keeps your data
brew uninstall --zap --cask spendifai  # also deletes ~/.spendifai
\`\`\`

This repository is generated: the cask is rendered and pushed by
\`packaging/homebrew/update-tap.sh\` in the main repository.
EOF

cd "${CLONE}"
if git diff --quiet && git diff --cached --quiet && [[ -z "$(git status --porcelain)" ]]; then
  ok "Tap already up to date for ${VERSION} — nothing to push"
  exit 0
fi

git add Casks/spendifai.rb README.md
git -c user.name="$(git -C "${REPO_ROOT}" config user.name)" \
    -c user.email="$(git -C "${REPO_ROOT}" config user.email)" \
    commit -q -m "spendifai ${VERSION}"
git push -q origin HEAD
ok "Pushed spendifai ${VERSION} to ${TAP_REPO}"

echo ""
echo "============================================================"
echo "  Tap updated — Spendif.ai ${VERSION}"
echo "============================================================"
echo ""
echo "  First install on a Mac:"
echo "    brew tap ${TAP_REPO%%/*}/${TAP_REPO##*-}"
echo "    brew trust --cask ${TAP_REPO%%/*}/${TAP_REPO##*-}/spendifai"
echo "    brew install --cask --no-quarantine spendifai"
echo ""
echo "  Later releases:"
echo "    brew update && brew upgrade --cask spendifai"
echo ""
